"use client";

import { useState } from "react";
import pricebookData from "../data/pricebook.json";

type Segment = "Open" | "Closed";
type Row = { id: string; date: string; provider: string; model: string; segment: Segment; input: number; output: number; outputMix: number; usage: number };
type HistoryPoint = { day: string; open: number; closed: number; all: number };
const data: Array<[string, string, string, Segment, number, number, number, number]> = [
  ["2026-08-18", "OpenAI", "Frontier API A", "Closed", 2.4, 9.6, .28, 26], ["2026-08-18", "Anthropic", "Frontier API B", "Closed", 3.1, 12.4, .31, 19], ["2026-08-18", "Google", "Efficient API", "Closed", .48, 3.6, .25, 16], ["2026-08-18", "Self-hosted", "Open Weight Large", "Open", .36, 1.2, .24, 21], ["2026-08-18", "Inference host", "Open Weight Small", "Open", .13, .54, .22, 18],
  ["2026-08-19", "OpenAI", "Frontier API A", "Closed", 2.4, 9.6, .29, 28], ["2026-08-19", "Anthropic", "Frontier API B", "Closed", 3.0, 12.1, .30, 20], ["2026-08-19", "Google", "Efficient API", "Closed", .46, 3.5, .25, 17], ["2026-08-19", "Self-hosted", "Open Weight Large", "Open", .34, 1.14, .23, 19], ["2026-08-19", "Inference host", "Open Weight Small", "Open", .12, .49, .21, 16],
  ["2026-08-20", "OpenAI", "Frontier API A", "Closed", 2.35, 9.4, .31, 31], ["2026-08-20", "Anthropic", "Frontier API B", "Closed", 2.98, 12.0, .31, 22], ["2026-08-20", "Google", "Efficient API", "Closed", .45, 3.4, .26, 15], ["2026-08-20", "Self-hosted", "Open Weight Large", "Open", .32, 1.05, .22, 18], ["2026-08-20", "Inference host", "Open Weight Small", "Open", .11, .45, .20, 14],
];
const seed: Row[] = pricebookData.rows.map((row, id) => ({ id: String(id), ...row, segment: row.segment as Segment }));
const price = (row: Row) => row.input * (1 - row.outputMix) + row.output * row.outputMix;
const weighted = (rows: Row[]) => rows.length ? rows.reduce((sum, row) => sum + price(row) * row.usage, 0) / rows.reduce((sum, row) => sum + row.usage, 0) : 0;
const money = (value: number) => `$${value.toFixed(2)}`;

export default function Home() {
  const [rows, setRows] = useState<Row[]>(seed); const [date, setDate] = useState(seed.at(-1)?.date || "");
  const dates = [...new Set(rows.map((row) => row.date))].sort(); const today = rows.filter((row) => row.date === date);
  const open = weighted(today.filter((row) => row.segment === "Open")); const closed = weighted(today.filter((row) => row.segment === "Closed")); const all = weighted(today);
  const history = dates.map((day) => { const list = rows.filter((row) => row.date === day); return { day, open: weighted(list.filter((row) => row.segment === "Open")), closed: weighted(list.filter((row) => row.segment === "Closed")), all: weighted(list) }; }); const max = Math.max(...history.flatMap((item) => [item.open, item.closed, item.all]), 1);
  const update = (id: string, field: keyof Row, value: string) => setRows((current) => current.map((row) => row.id === id ? { ...row, [field]: ["input", "output", "outputMix", "usage"].includes(field) ? Number(value) : value } as Row : row));
  const addRow = () => setRows((current) => [...current, { id: crypto.randomUUID(), date, provider: "New provider", model: "New model", segment: "Open", input: .25, output: 1, outputMix: .25, usage: 1 }]);
  const removeRow = (id: string) => setRows((current) => current.filter((row) => row.id !== id)); const reset = () => { setRows(seed); setDate(seed.at(-1)?.date || ""); };
  return <main>
    <header className="topbar"><div><a className="brand" href="#top">TOKEN PRICEBOOK</a><span className="edition">DAILY CALCULATOR</span></div><button className="plain-button" onClick={reset}>저장된 데이터로 초기화</button></header>
    <section className="hero" id="top"><p className="eyebrow">MODEL-LEVEL TOKEN ECONOMICS</p><h1>일별 모델 가격을<br /><em>직접 계산하세요.</em></h1><p>입력·출력 토큰 단가와 실제 사용 비중을 넣으면, 모델별 정규화 가격과 Open / Closed / 전체 가중평균 지수를 즉시 계산합니다.</p></section>
    <section className="workspace"><div className="toolbar"><div><p className="section-label">CALCULATION DATE</p><input aria-label="계산 날짜" className="date-input" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></div><div className="formula-note"><b>정규화 가격</b> = 입력 단가 × (1 − 출력 비중) + 출력 단가 × 출력 비중<br /><span>단가 단위: USD / 1M tokens · 사용 가중치: 상대값</span></div></div>
      <div className="metrics" aria-label="계산된 가격지수"><Metric label="OPEN LLM" value={open} color="mint" /><Metric label="CLOSED LLM" value={closed} color="lime" /><Metric label="ALL MODELS" value={all} color="dark" /></div>
      <section className="table-section"><div className="section-heading"><div><p className="section-label">DAILY PRICEBOOK</p><h2>{date} · 모델별 단가</h2></div><button className="add-button" onClick={addRow}>+ 모델 추가</button></div><div className="table-wrap"><table><thead><tr><th>구분</th><th>제공사 / 모델</th><th>입력 단가</th><th>출력 단가</th><th>출력 비중</th><th>사용 가중치</th><th>정규화 가격</th><th /></tr></thead><tbody>{today.map((row) => <tr key={row.id}><td><select value={row.segment} onChange={(event) => update(row.id, "segment", event.target.value)}><option>Open</option><option>Closed</option></select></td><td><input value={row.provider} onChange={(event) => update(row.id, "provider", event.target.value)} aria-label="제공사"/><input value={row.model} onChange={(event) => update(row.id, "model", event.target.value)} aria-label="모델" className="model-input"/></td><td><NumberInput value={row.input} onChange={(value) => update(row.id, "input", value)} /></td><td><NumberInput value={row.output} onChange={(value) => update(row.id, "output", value)} /></td><td><NumberInput value={row.outputMix} onChange={(value) => update(row.id, "outputMix", value)} step="0.01" /></td><td><NumberInput value={row.usage} onChange={(value) => update(row.id, "usage", value)} /></td><td className="result">{money(price(row))}</td><td><button className="delete-button" aria-label={`${row.model} 삭제`} onClick={() => removeRow(row.id)}>×</button></td></tr>)}</tbody></table></div>{!today.length && <div className="empty"><p>이 날짜에는 아직 모델이 없습니다.</p><button className="add-button" onClick={addRow}>첫 모델 추가</button></div>}</section>
    </section>
    <section className="history"><div className="history-heading"><p className="section-label">DAILY VIEW</p><h2>날짜별 가격 흐름</h2><p>각 막대는 해당 날짜의 사용 가중치를 반영한 평균 단가입니다.</p></div><div className="chart" role="img" aria-label="Open, Closed, 전체 모델의 일별 정규화 가격 비교 차트">{history.map((item) => <div className="day" key={item.day}><div className="bars"><Bar value={item.open} max={max} type="open" /><Bar value={item.closed} max={max} type="closed" /><Bar value={item.all} max={max} type="all" /></div><time>{item.day.slice(5).replace("-", "/")}</time></div>)}</div><div className="legend"><span><i className="open-dot" />Open</span><span><i className="closed-dot" />Closed</span><span><i className="all-dot" />전체</span></div></section>
    <TrendChart history={history} max={max} selectedDate={date} onDateChange={setDate} />
    <section className="method"><p className="section-label">HOW TO USE</p><ol><li><b>하루를 선택</b><span>날짜별로 가격표를 분리해 입력합니다.</span></li><li><b>단가와 믹스를 입력</b><span>입력·출력 단가, 출력 토큰 비중, 사용 가중치를 넣습니다.</span></li><li><b>지수 변화 확인</b><span>각 모델의 정규화 가격과 세 부문의 일별 평균을 비교합니다.</span></li></ol><p className="disclaimer">일별 원본은 data/pricebook.json에 누적 보존되며, GitHub Actions가 매일 OpenRouter의 공개 모델 가격을 새 날짜로 추가합니다. 이 가격은 Silicon Data 지수와 동일한 원자료가 아니라, 공개 가격표 기반의 참고용 시계열입니다.</p></section>
  </main>;
}
function Metric({ label, value, color }: { label: string; value: number; color: string }) { return <div className={`metric ${color}`}><span>{label}</span><strong>{money(value)}</strong><small>USD / 1M tokens</small></div>; }
function NumberInput({ value, onChange, step = "0.1" }: { value: number; onChange: (value: string) => void; step?: string }) { return <input className="number" type="number" min="0" step={step} value={value} onChange={(event) => onChange(event.target.value)} />; }
function Bar({ value, max, type }: { value: number; max: number; type: string }) { return <span className={`bar ${type}`} style={{ height: `${Math.max(8, value / max * 100)}%` }} title={money(value)} />; }
function TrendChart({ history, max, selectedDate, onDateChange }: { history: HistoryPoint[]; max: number; selectedDate: string; onDateChange: (date: string) => void }) {
  const width = 900, height = 280, left = 46, right = 18, top = 20, bottom = 42;
  const innerWidth = width - left - right, innerHeight = height - top - bottom;
  const x = (index: number) => history.length < 2 ? left + innerWidth / 2 : left + (index / (history.length - 1)) * innerWidth;
  const y = (value: number) => top + innerHeight - (value / max) * innerHeight;
  const path = (key: keyof Pick<HistoryPoint, "open" | "closed" | "all">) => history.map((item, index) => `${index ? "L" : "M"}${x(index)},${y(item[key])}`).join(" ");
  const series = [{ key: "open" as const, label: "Open", color: "#83b686" }, { key: "closed" as const, label: "Closed", color: "#bad84a" }, { key: "all" as const, label: "전체", color: "#172722" }];
  return <section className="trend-section"><div className="trend-header"><div><p className="section-label">INDEX TREND</p><h2>선으로 보는 추이</h2></div><p>날짜를 클릭하면 해당 날짜의 모델별 가격표로 이동합니다.</p></div><div className="trend-legend">{series.map((item) => <span key={item.key}><i style={{ background: item.color }} />{item.label}</span>)}</div><div className="trend-wrap"><svg className="trend-svg" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="일별 Open, Closed, 전체 지수 추이 선 그래프"><g className="trend-grid">{[0, .25, .5, .75, 1].map((step) => <line key={step} x1={left} x2={width - right} y1={y(max * step)} y2={y(max * step)} />)}</g><g className="trend-labels">{[0, .5, 1].map((step) => <text key={step} x="0" y={y(max * step) + 4}>{money(max * step)}</text>)}</g>{series.map((item) => <g key={item.key}><path d={path(item.key)} stroke={item.color} fill="none" strokeWidth={item.key === "all" ? 4 : 3} strokeLinecap="round" strokeLinejoin="round" />{history.map((point, index) => <circle key={`${item.key}-${point.day}`} cx={x(index)} cy={y(point[item.key])} r={selectedDate === point.day ? 6 : 4} fill={item.color} stroke="#f7f4ed" strokeWidth="2" onClick={() => onDateChange(point.day)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") onDateChange(point.day); }} tabIndex={0} role="button" aria-label={`${point.day} ${item.label} ${money(point[item.key])}`}><title>{`${point.day} · ${item.label} ${money(point[item.key])}`}</title></circle>)}</g>)}{history.map((point, index) => <text key={point.day} className={`trend-date ${selectedDate === point.day ? "selected" : ""}`} x={x(index)} y={height - 10} textAnchor="middle" onClick={() => onDateChange(point.day)}>{point.day.slice(5).replace("-", "/")}</text>)}</svg></div></section>;
}
